//Afficher message de bienvenue dans le console.log
let message = "Bienvenue dans votre gestionnaire de tâches!"
console.log(message);

// Créer une variable de nombre entier et l'afficher

let nbTache = [12, 13, 16]
let nombreGestion = nbTache.length

console.log("nbTache :" + nombreGestion);


//Déclaration d'un tableau de tâches
let nombreDeTâches = []
let nbTaches = nombreDeTâches.length
if (nbTaches===0){

    console.log("Aucune tâche à faire.");
    
} else {

    console.log("nombre de tâches :" + nbTaches); 
}

//Création d'un tableau vide et ajouter une tâche

const taches =["Tache 1", "Tache 2", "Tache 3"]

taches.push("Faire les courses");

console.log(taches);



